config/routes.rb
Mcm::Application.routes.draw do
  root :to => "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"},
  :path_names => { :sign_in => 'login',
    :sign_out => 'logout', :password => 'secret', :confirmation => 'verification',
    :unlock => 'unblock', :sign_up => 'cmon_let_me_in' }

  resources :users do
    member do
      get :load_users
      get :load_data_table
      get :details_information
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :load_users
        get :add_phone
      end
    end
    resources :tariffs do

    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tariffs_users, :dependent => :destroy
  has_many :tariffs, :through => :tariffs_users
  has_many :phones, :dependent => :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :tariff_ids
  attr_accessible :email, :password, :password_confirmation, :remember_me, :parent_id,
                  :full_name, :tariff_ids
  attr_protected :admin, :date_of_trip

  validates :parent_id, :presence => true
  validates :full_name, :presence => true
  validates_numericality_of :parent_id, :greater_than => 0, :if => Proc.new { |user| !user.admin? }
  validates_numericality_of :parent_id, :only_integer => true

  acts_as_tree :order => "email", :dependent => false

  validate :parent_user
  validate :select_tariff_ids

  after_create :create_tariff

  accepts_nested_attributes_for :phones, :allow_destroy => true, :reject_if => proc { |attributes| attributes['number'].blank? }

  COEF_CARD = {"1" => 5, "2" => 1, "3" => 1, "4" => 1, "5" => 1}
  COEF_BALANS = {"1" => 5, "2" => 1, "3" => 0.5, "4" => 0.25, "5" => 0.12}

  def update_without_current_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    params.delete(:current_password) if params[:current_password].blank?
    self.update_attributes(params)
  end

  def create_tariff
    tariffs_users.clear
    tariff_ids.uniq.each do |t|
      tariffs_users.create(:tariff_id => t)
    end
  end

  def active?
    self.date_of_trip > Time.now
  end

  private

  def parent_user
    errors.add(:parent_id, "не найден") if User.find_by_id(self.parent_id).nil? &&
      !self.parent_id.nil? && !self.parent_id.zero? || self.parent_id == self.id
  end

  def select_tariff_ids
    self.tariff_ids = self.tariff_ids.split(',') if self.tariff_ids.is_a?(String)
    puts "===="
    puts self.tariff_ids.inspect
    errors.add(:tariff_ids, "должен быть выбран") if self.tariff_ids.reject{|value| value.blank? }.empty?
    errors.add(:tariff_ids, "не известен") if (Tariff.mobile_kyivstar_tariff.find_all_by_id(self.tariff_ids).count > 1) ||
      (Tariff.mobile_life_tariff.find_all_by_id(self.tariff_ids).count > 1)
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :load_user, :only => [:edit, :update, :destroy]

  def index
    @users = User.all
    #render :layout => 'ui_templates'
  end

  def new
    @user = User.new
    @phones = @user.phones.build
  end

  def create
    @user = User.new(params[:user])
    @user.admin = params[:user][:admin]
    @user.date_of_trip = params[:user][:date_of_trip]
    if @user.save
      flash[:notice] = "Пользователь создан"
      redirect_to edit_admin_user_path(@user)
    else
      @phones = @user.phones.build if @user.phones.empty?
      flash[:error] = "Пользователь не создан"
      render :action => :new
    end
  end

  def edit
    @phones = @user.phones
    @phones = @user.phones.build if @phones.empty?
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation) if params[:password_confirmation].blank?
    end if params[:user]

    if @user.update_attributes(params[:user])
      @user.admin = params[:user][:admin]
      @user.date_of_trip = params[:user][:date_of_trip]
      @user.save
      @user.create_tariff
      flash[:notice] = "Пользователь обновлен"
      redirect_to edit_admin_user_path(@user)
    else
      flash[:error] = "Пользователь не обновлен"
      render :action => :edit
    end
  end

  def destroy
    unless @user.parent_id.zero?
      if @user.children.update_all(:parent_id => @user.parent_id)
        if @user.destroy
          flash[:notice] = "Пользователь удален"
        else
          flash[:error] = "Пользователь не удален"
        end
      end
    else
      flash[:error] = "Главный пользователь системы не может быть уделен"
    end
    redirect_to :action => :index
  end

  def load_users
    @users = []
    @users = User.where(["email like ?", "%#{params[:user_email]}%"])
    @users = @users.map{|u| {:label => u.email, :value => u.id}} unless @users.nil?
    render :json => @users
  end

  def add_phone; end

  private

  def load_user
    @user = User.find_by_id(params[:id])
  end

  def set_tariff

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :load_user, :only => [:load_users, :load_data_table]

  def index
  end

  def load_users
    render :json => [{:title => @user.full_name, :id => @user.id, :children => load_children(@user)} ]
  end

  def load_data_table
    levels = {"1" => [], "2" => [], "3" => [], "4" => [], "5" => []}
    h = {:aaData => []}
    get_level_users(@user, levels).each_pair do |level, users|
      active_users = 0
      users.each{|u| active_users = active_users+1 if u.active?}
      users_count = users.size
      h[:aaData] << [level, users_count, active_users, users_count - active_users, 
        active_users * User::COEF_CARD["#{level}"], active_users * User::COEF_BALANS["#{level}"] ]
    end
    render :json => h
  end

  def details_information
    @user = User.find_by_id(params[:id])
    render :layout => false
  end

  private

  def get_level_users(user, levels, level = 1)
    user.children.each do |child|
      levels["#{level}"] << child
      get_level_users(child, levels, level+1) if level+1 <= 5
    end
    levels
  end

  def load_children(user, level = 0)
    children = []
    user.children.each do |child|
      children << {:title => child.full_name, :id => child.id, :children => load_children(child, level+1)} if level+1 <= 5
    end
    children
  end

  def load_user
    begin
      @user = User.find_by_id(params[:id])
      raise if @user.nil? || @user.id != current_user.id
    rescue
      redirect_to root_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_details_user_information.html.erb
<style type="text/css">
  div.box {height:115px;}
  div.box {padding:0;}
  .tabular label{width:210px; margin-right:10px;}
</style>

<div class="box tabular">
  <p style="overflow: visible">
    <label for="email">Почтовый адрес<span class="required"> </span></label>
    <%= user.email %>
    <em></em>
  </p>

  <p style="overflow: visible">
    <label for="parent_id">Тарифный план<span class="required"> </span></label>
    <%= user.tariffs.map { |t| "#{t.title}(#{t.value})" }.join(", ") %><br/>
    <em></em>
  </p>

  <p style="overflow: visible">
    <label for="full_name">Контактные номера<span class="required"> </span></label>
    <%= user.phones.map(&:number).join(', ') unless user.phones.empty? %>
    <em></em>
  </p>
  <p style="overflow: visible">
    <label for="full_name">Личный информационный номер<span class="required"> </span></label>
    <%= user.id %>
    <em></em>
  </p>
  <p style="overflow: visible">
    <label for="full_name">Ф.И.О спонсора<span class="required"> </span></label>
    <%= user.parent.full_name unless user.parent.nil? %>
    <em></em>
  </p>
  <p style="overflow: visible">
    <label for="full_name">Контактные номера спонсора<span class="required"> </span></label>
    <%= user.parent.phones.map(&:number).join(', ') if !user.parent.nil? && !user.parent.phones.empty? %>
    <em></em>
  </p>
  <p style="overflow: visible">
    <label for="full_name">Актиность<span class="required"> </span></label>
      <%= raw user.active? ? user.date_of_trip.to_date : "<span style='color:red;'>Пользователь неактивен</span" %>
    <em></em>
  </p>
</div>

app/views/users/_users_tree.html.erb
<script type="text/javascript">
  $(function() {
    $("#tree").dynatree({
      fx: { height: "toggle", duration: 200 },
      onActivate: function(node) {
        $.ajax({
          url: "/users/"+node.data.id+"/details_information",
          success: function(data){},
          dataType: 'script'
        });
      },
      initAjax: {
        url: "<%= load_users_user_path(current_user) %>"
      }
    });
  });
</script>

<div id="tree"></div>

app/views/users/details_information.js.erb
$('#details_user_information').html('<%= escape_javascript(render :partial => "details_user_information",
  :locals => {:user => @user}) %>');
$('#list-right').effect("highlight", {}, 1000);

app/views/users/index.html.erb
<% content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => nil} %>
<% end %>

<%= content_for :more_javascripts do %>
  <%= javascript_include_tag "jquery.dynatree" %>
  <%= stylesheet_link_tag "ui.dynatree" %>
  <%= javascript_include_tag "jquery.dataTables" %>
  <%= stylesheet_link_tag "datatable/demo_table" %>
  <%= stylesheet_link_tag "datatable/demo_table_jui" %>
  <%= stylesheet_link_tag "datatable/demo_page" %>
<% end %>

<%= content_for :title_page do %>
  <h2>Информационная страница</h2>
<% end %>

<div id="list-top"></div>
<div id="list-left" class="splitcontentleft">
  <div class="mypage-box">
    <h3>Древовидная Схема Рефералов</h3>
    <%= render :partial => "users_tree" %>
  </div>
</div>
<div id="list-right" class="splitcontentright">
  <div class="mypage-box">
    <h3>Информация о пользователе</h3>
    <div id="details_user_information">
      <p class="nodata">Пользователь не выбран</p>
    </div>
  </div>
</div>

<table class='data-table display' style="width: 100%">
  <thead>
  <tr>
    <th>Уровень</th>
    <th>Количество Пользоветелей</th>
    <th>Активных</th>
    <th>Не активных</th>
    <th>Карточка</th>
    <th>Счет</th>
  </tr>
  </thead>
  <tbody>
  <tr></tr>
  </tbody>
  <tfoot>
  <tr></tr>
  </tfoot>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $('.data-table').dataTable({
      bSort: false,
      //bJQueryUI: true,
      //bProcessing: true,
      bPaginate: false,
      bFilter: false,
      bAutoWidth: true,
      bInfo: false,
      sAjaxSource: "users/<%= current_user.id %>/load_data_table/"
    });
  });
</script>