config/routes.rb
Mcm::Application.routes.draw do
  root :to => "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"},
  :path_names => { :sign_in => 'login',
    :sign_out => 'logout', :password => 'secret', :confirmation => 'verification',
    :unlock => 'unblock', :sign_up => 'cmon_let_me_in' }

  resources :users do
    member do
      get :load_users
      get :load_data_table
      get :details_information
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :load_users
        get :add_phone
      end
    end
    resources :tariffs do

    end
  end

end

app/models/tariff.rb
class Tariff < ActiveRecord::Base
  has_many :tariffs_users, :dependent => :destroy
  has_many :users, :through => :tariffs_users

  validates :value, :presence => true
  validates :tariff_type, :presence => true
  validates :title, :presence => true
  validates_numericality_of :value, :only_integer => true, :greater_than => 0

  MOBILE_CONNECTION = "Мобильная связь"
  KYIVSTAR = "Kyivstar"
  LIFE = "Life"

  scope :mobile_tariff, where(:tariff_type => MOBILE_CONNECTION)
  scope :mobile_kyivstar_tariff, where(:tariff_type => MOBILE_CONNECTION, :title => KYIVSTAR)
  scope :mobile_life_tariff, where(:tariff_type => MOBILE_CONNECTION, :title => LIFE)
end

app/controllers/admin/tariffs_controller.rb
class Admin::TariffsController < ApplicationController
  before_filter :load_tariff, :only => [:edit, :update, :destroy]

  def index
    @tariffs = Tariff.order("tariff_type, title, value").all
  end

  def new
    @tariff = Tariff.new
  end

  def create
    @tariff = Tariff.new(params[:tariff])
    if @tariff.save
      flash[:notice] = "Тариф создан"
      redirect_to :action => :edit, :id => @tariff.id
    else
      flash[:error] = "Тариф не создан"
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @tariff.update_attributes(params[:tariff])
      flash[:notice] = "Тарфи обновлен"
      redirect_to :action => :edit, :id => @tariff
    else
      flash[:error] = "Тарфи не обновлен"
      render :action => :edit
    end
  end

  def destroy
    if @tariff.destroy
      flash[:notice] = "Тариф удален"
    else
      flash[:error] = "Тариф не удален"
    end
    redirect_to :action => :index
  end

  private

  def load_tariff
    @tariff = Tariff.find_by_id(params[:id])
  end

end

app/helpers/admin/tariffs_helper.rb
module Admin::TariffsHelper

  def mobile_tariff_options(operator)
    options = Tariff.where(:tariff_type => Tariff::MOBILE_CONNECTION, :title => operator).order("tariff_type, title, value").
      map{|t| [t.value, t.id]}
    options.insert(0, ["Не выбран", nil])
  end

end

app/views/admin/tariffs/_form.html.erb
<p>
  <label for="email">Тип<span class="required"> *</span></label>
  <%= f.text_field :tariff_type %>
  <em></em>
</p>

<p>
  <label for="parent_id">Название<span class="required"> *</span></label>
  <%= f.text_field :title %><br />
  <em></em>
</p>

<p>
  <label for="full_name">Стоимость<span class="required"> *</span></label>
  <%= f.text_field :value %>
  <em></em>
</p>

app/views/admin/tariffs/_tariff.html.erb
<tr class="<%= cycle('odd', 'even')%>">
  <td><span><%= tariff.tariff_type %></span></td>
  <td align="center" style="width:15%;"><%= tariff.title %></td>
  <td align="center" style="width:15%;"><%= tariff.value %></td>
  <td class="buttons">
    <%= link_to "Редактировать", edit_admin_tariff_path(tariff) %>
    <%= link_to "Удалить", admin_tariff_path(tariff), :method => "delete", :confirm => "Вы уверенны?" %>
  </td>
</tr>

app/views/admin/tariffs/edit.html.erb
<% content_for :title_page do %>
  <h2>Редактирование  тарифа <%= @tariff.title %></h2>
<% end %>

<% content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @tariff} %>
<% end %>

<%= form_for @tariff, :url => {:action => :update}, :html => {:class => 'tabular'} do |f| %>
  <div class="box">
    <%= render :partial => 'form', :locals => {:f =>f} %>
    <%= f.submit 'Обновить' %>&nbsp;|
    <%= link_to "Назад", admin_tariffs_path %>
  </div>
<% end %>

app/views/admin/tariffs/index.html.erb
<% content_for :contextual do %>
  <%= link_to "Новый тариф", new_admin_tariff_path, :class => "icon icon-add" %>
<% end %>

<% content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @tariff}%>
<% end %>

<h2>Тарифы</h2>

<table class="list">
  <thead>
    <tr>
      <th>Тип</th>
      <th>Название</th>
      <th>Стоимость</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= render :partial => "tariff", :collection => @tariffs %>
  </tbody>
</table>
 <p class="pagination"></p>

app/views/admin/tariffs/new.html.erb
<%= content_for :title_page do %>
  <h2>Новый тариф</h2>
<% end %>

<%= content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @tariff} %>
<% end %>

<%= form_for @tariff, :url => {:action => :create}, :html => {:class => 'tabular'} do |f| %>
  <div class="box">
    <%= render :partial => 'form', :locals => {:f =>f} %>
    <%= f.submit 'Создать' %>&nbsp;|
    <%= link_to "Назад", admin_tariffs_path %>
  </div>
<% end %>