config/routes.rb
Mcm::Application.routes.draw do
  root :to => "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"},
  :path_names => { :sign_in => 'login',
    :sign_out => 'logout', :password => 'secret', :confirmation => 'verification',
    :unlock => 'unblock', :sign_up => 'cmon_let_me_in' }

  resources :users do
    member do
      get :load_users
      get :load_data_table
      get :details_information
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :load_users
        get :add_phone
      end
    end
    resources :tariffs do

    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tariffs_users, :dependent => :destroy
  has_many :tariffs, :through => :tariffs_users
  has_many :phones, :dependent => :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :tariff_ids
  attr_accessible :email, :password, :password_confirmation, :remember_me, :parent_id,
                  :full_name, :tariff_ids
  attr_protected :admin, :date_of_trip

  validates :parent_id, :presence => true
  validates :full_name, :presence => true
  validates_numericality_of :parent_id, :greater_than => 0, :if => Proc.new { |user| !user.admin? }
  validates_numericality_of :parent_id, :only_integer => true

  acts_as_tree :order => "email", :dependent => false

  validate :parent_user
  validate :select_tariff_ids

  after_create :create_tariff

  accepts_nested_attributes_for :phones, :allow_destroy => true, :reject_if => proc { |attributes| attributes['number'].blank? }

  COEF_CARD = {"1" => 5, "2" => 1, "3" => 1, "4" => 1, "5" => 1}
  COEF_BALANS = {"1" => 5, "2" => 1, "3" => 0.5, "4" => 0.25, "5" => 0.12}

  def update_without_current_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    params.delete(:current_password) if params[:current_password].blank?
    self.update_attributes(params)
  end

  def create_tariff
    tariffs_users.clear
    tariff_ids.uniq.each do |t|
      tariffs_users.create(:tariff_id => t)
    end
  end

  def active?
    self.date_of_trip > Time.now
  end

  private

  def parent_user
    errors.add(:parent_id, "не найден") if User.find_by_id(self.parent_id).nil? &&
      !self.parent_id.nil? && !self.parent_id.zero? || self.parent_id == self.id
  end

  def select_tariff_ids
    self.tariff_ids = self.tariff_ids.split(',') if self.tariff_ids.is_a?(String)
    puts "===="
    puts self.tariff_ids.inspect
    errors.add(:tariff_ids, "должен быть выбран") if self.tariff_ids.reject{|value| value.blank? }.empty?
    errors.add(:tariff_ids, "не известен") if (Tariff.mobile_kyivstar_tariff.find_all_by_id(self.tariff_ids).count > 1) ||
      (Tariff.mobile_life_tariff.find_all_by_id(self.tariff_ids).count > 1)
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :load_user, :only => [:edit, :update, :destroy]

  def index
    @users = User.all
    #render :layout => 'ui_templates'
  end

  def new
    @user = User.new
    @phones = @user.phones.build
  end

  def create
    @user = User.new(params[:user])
    @user.admin = params[:user][:admin]
    @user.date_of_trip = params[:user][:date_of_trip]
    if @user.save
      flash[:notice] = "Пользователь создан"
      redirect_to edit_admin_user_path(@user)
    else
      @phones = @user.phones.build if @user.phones.empty?
      flash[:error] = "Пользователь не создан"
      render :action => :new
    end
  end

  def edit
    @phones = @user.phones
    @phones = @user.phones.build if @phones.empty?
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation) if params[:password_confirmation].blank?
    end if params[:user]

    if @user.update_attributes(params[:user])
      @user.admin = params[:user][:admin]
      @user.date_of_trip = params[:user][:date_of_trip]
      @user.save
      @user.create_tariff
      flash[:notice] = "Пользователь обновлен"
      redirect_to edit_admin_user_path(@user)
    else
      flash[:error] = "Пользователь не обновлен"
      render :action => :edit
    end
  end

  def destroy
    unless @user.parent_id.zero?
      if @user.children.update_all(:parent_id => @user.parent_id)
        if @user.destroy
          flash[:notice] = "Пользователь удален"
        else
          flash[:error] = "Пользователь не удален"
        end
      end
    else
      flash[:error] = "Главный пользователь системы не может быть уделен"
    end
    redirect_to :action => :index
  end

  def load_users
    @users = []
    @users = User.where(["email like ?", "%#{params[:user_email]}%"])
    @users = @users.map{|u| {:label => u.email, :value => u.id}} unless @users.nil?
    render :json => @users
  end

  def add_phone; end

  private

  def load_user
    @user = User.find_by_id(params[:id])
  end

  def set_tariff

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :load_user, :only => [:load_users, :load_data_table]

  def index
  end

  def load_users
    render :json => [{:title => @user.full_name, :id => @user.id, :children => load_children(@user)} ]
  end

  def load_data_table
    levels = {"1" => [], "2" => [], "3" => [], "4" => [], "5" => []}
    h = {:aaData => []}
    get_level_users(@user, levels).each_pair do |level, users|
      active_users = 0
      users.each{|u| active_users = active_users+1 if u.active?}
      users_count = users.size
      h[:aaData] << [level, users_count, active_users, users_count - active_users, 
        active_users * User::COEF_CARD["#{level}"], active_users * User::COEF_BALANS["#{level}"] ]
    end
    render :json => h
  end

  def details_information
    @user = User.find_by_id(params[:id])
    render :layout => false
  end

  private

  def get_level_users(user, levels, level = 1)
    user.children.each do |child|
      levels["#{level}"] << child
      get_level_users(child, levels, level+1) if level+1 <= 5
    end
    levels
  end

  def load_children(user, level = 0)
    children = []
    user.children.each do |child|
      children << {:title => child.full_name, :id => child.id, :children => load_children(child, level+1)} if level+1 <= 5
    end
    children
  end

  def load_user
    begin
      @user = User.find_by_id(params[:id])
      raise if @user.nil? || @user.id != current_user.id
    rescue
      redirect_to root_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_add_phone.html.erb
<% id = generate_rendom_id %>
<span id="span_<%= id %>">
  <%= raw text_field_tag "user[phones_attributes][#{id}][number]", "", :size => 30, :id => id  %>
  <%= link_to_function "Удалить номер", "$('#span_#{id}').remove(); return false;" %><br />
</span>

app/views/admin/users/_form.html.erb
<p>
  <label for="email">Почтовый адрес<span class="required"> *</span></label>
  <%= f.text_field :email %>
  <em></em>
</p>

<p>
  <label for="password">Пароль<span class="required"> *</span></label>
  <%= f.password_field :password, :autocomplete => "off" %>
  <em></em>
</p>

<p>
  <label for="password_confirmation">
    Подтвердить Пароль<span class="required"> *</span>
  </label>
  <%= f.password_field :password_confirmation, :autocomplete => "off" %>
  <em></em>
</p>

<p>
  <label for="parent_id">Информационный номер спонсора<span class="required"> *</span></label>
  <%= f.text_field :parent_id %><br/>
  <em>Указать номер связи с пользователем или начать ввод почтового адреса</em>
</p>

<p>
  <label for="full_name">Ф.И.О<span class="required"> *</span></label>
  <%= f.text_field :full_name %>
  <em></em>
</p>

<div>
  <div style="float:left;">
    <p><%= label_tag "Тарфиный план" %></p>
  </div>
  <div style="float:left; margin-left:10px;">
    <table class="list" style="width:255px;">
      <thead>
      <tr>
        <th>Kyivstar</th>
        <th>Life</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= select_tag "user[tariff_ids][]", options_for_select(mobile_tariff_options("Kyivstar"),
                                                                    params[:user] ? params[:user][:tariff_ids] :
                                                                            f.object.tariffs_users.map(&:tariff_id)),
                           {:style => "width:100%"} %>
        </td>
        <td><%= select_tag "user[tariff_ids][]", options_for_select(mobile_tariff_options("Life"),
                                                                    params[:user] ? params[:user][:tariff_ids] :
                                                                            f.object.tariffs_users.map(&:tariff_id)),
                           {:style => "width:100%"} %></td>
      </tr>
      </tbody>
    </table>
    <em>Тарифные планы можно комбинировать</em>
  </div>
</div>

<p>
  <label for="admin">
    Контактные номера
  <span class="required"> &nbsp;</span><br />
  <%= link_to "Добавить номер", add_phone_admin_users_path, :remote => true %>&nbsp;&nbsp;&nbsp;
  </label>
  <span id="phones">
  <%= f.fields_for :phones do |f_p| %>
      <% id = generate_rendom_id %>
      <%= f_p.hidden_field :_destroy, :id => id %>
      <%= raw f_p.text_field :number, :id => "field_#{id}" %>
      <span id="delete_span_<%= id %>">
        <%= link_to_function "Удалить номер", "$('##{id}').val(true); $('#field_#{id}').css('background', 'red');
        $('#delete_span_#{id}').toggle(); $('#return_span_#{id}').toggle(); return false;" %>
      </span>
      <span id="return_span_<%= id %>" style="display:none;">
        <%= link_to_function "Отменить", "$('##{id}').val(false); $('#field_#{id}').css('background', 'white');
        $('#delete_span_#{id}').toggle(); $('#return_span_#{id}').toggle(); return false;" %>
      </span>
      <br />
  <% end %>
  </span>
</p>

<p>
  <label for="active">Дата отключения<span class="required"> &nbsp;</span></label>
  <%= f.text_field :date_of_trip, :value => f.object.date_of_trip.to_date,
    :readonly => true %>
  <em></em>
</p>

<p>
  <label for="admin">Администратор<span class="required">&nbsp;</span></label>
  <%= f.check_box :admin %>
  <em></em>
</p>

<script>
  $("input#user_parent_id").autocomplete({
    source: function(request, response) {
      $.ajax({
        type: 'GET',
        data: {user_email:$('#user_parent_id').val()},
        url: '/admin/users/load_users',
        success: function(data) {
          response(data);
        },
        dataType: "json"
      });
    }
  });
  $(document).ready(function() {
    $('#user_date_of_trip').datepicker({
	  showOn: "button",
	  buttonImage: "/images/calendar.png",
	  buttonImageOnly: true,
      dateFormat: "yy-mm-dd"
	});
  });
</script>

app/views/admin/users/_user.html.erb
<tr class="<%= cycle('odd', 'even')%>">
  <td><span><%= user.email %></span></td>
  <td align="center" style="width:15%;"><%= user.full_name %></td>
  <td class="buttons">
    <%= link_to "Редактировать", edit_admin_user_path(user) %>
    <%= link_to "Удалить", admin_user_path(user), :method => "delete", :confirm => "Вы уверенны?" %>
  </td>
</tr>

app/views/admin/users/add_phone.js.erb
$("#phones").append('<%= escape_javascript render :partial => "add_phone" %>');

app/views/admin/users/edit.html.erb
<% content_for :title_page do %>
  <h2>Редактирование пользователя <%= @user.email %></h2>
<% end %>

<% content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @user} %>
<% end %>

<%= form_for @user, :url => {:action => :update}, :html => {:class => 'tabular'} do |f| %>
  <div class="box">
    <%= render :partial => 'form', :locals => {:f =>f} %>
    <%= f.submit 'Обновить' %>&nbsp;|
    <%= link_to "Назад", admin_users_path %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :contextual do %>
  <%= link_to "Новый пользователь", new_admin_user_path, :class => "icon icon-add" %>
<% end %>

<% content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @user}%>
<% end %>

<h2>Пользователи</h2>

<table class="list">
  <thead>
    <tr>
      <th>Почтовый адрес</th>
      <th>Ф.И.О</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= render :partial => "user", :collection => @users %>
  </tbody>
</table>
 <p class="pagination"></p>

app/views/admin/users/new.html.erb
<%= content_for :title_page do %>
  <h2>Новый пользователь</h2>
<% end %>

<%= content_for :flash_message do %>
  <%= render :partial => "common/flash_messages", :locals => {:object => @user} %>
<% end %>

<%= form_for @user, :url => {:action => :create}, :html => {:class => 'tabular'} do |f| %>
  <div class="box">
    <%= render :partial => 'form', :locals => {:f =>f} %>
    <%= f.submit 'Создать' %>&nbsp;|
    <%= link_to "Назад", admin_users_path %>
  </div>
<% end %>